baseURL = "https://f4ww4z.me/"
title = "Fawwaz's Journey"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

# directories
publishDir = "docs"

googleAnalytics = "UA-112537769-1"
disqusShortname = "f4ww4z-me"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "A marvelous journey through the world of open source"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = "Copyright"
holder = "Maharaj Fawwaz Almuqaddim Yusran"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "faww4zintelgent4@gmail.com"
github = "f4ww4z"
telegram = "f4ww4z"

[params.social.config]
platforms = ["github","email","telegram"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

# Menus
[[menu.main]]
    name = "Home"
    weight = -10
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Posts"
    weight = -5
    identifier = "posts"
    url = "/post/"

[[menu.main]]
    name = "Categories"
    weight = -4
    identifier = "categories"
    url = "/categories/"

[[menu.main]]
    name = "Tags"
    weight = -3
    identifier = "tags"
    url = "/tags/"

[[menu.main]]
    name = "About"
    weight = -2
    identifier = "about"
    url = "/about/"

[[menu.main]]
  name = "Repo"
  weight = -1
  identifier = "repository"
  url = "https://github.com/f4ww4z/blog/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
